return {
    RndWeaponReroll_Name = "Reroll",
    RndWeaponReroll_Description = "Switch between 4 random sequences. No limit to the number of uses, but only one unit can be selected as the target repeatedly each turn. Mech can act again after use.",
    RndWeaponReroll_Upgrade1 = "+1 Sequence",
    RndWeaponReroll_Upgrade2 = "+1 Sequence",
    RndWeaponReroll_A_UpgradeDescription = "Increase number of random sequences by 1.",
    RndWeaponReroll_B_UpgradeDescription = "Increase number of random sequences by 1.",

    RndWeaponPrime_Name = "RND[Prime]",
    RndWeaponPrime_Description = "Use random Prime class weapon.",
    RndWeaponPrime_Upgrade1 = "Upgrade 1",
    RndWeaponPrime_Upgrade2 = "Upgrade 2",
    RndWeaponPrime_A_UpgradeDescription = "Random Prime class weapon Upgrade 1.",
    RndWeaponPrime_B_UpgradeDescription = "Random Prime class weapon Upgrade 2.",

    RndWeaponBrute_Name = "RND[Brute]",
    RndWeaponBrute_Description = "Use random Brute class weapon.",
    RndWeaponBrute_Upgrade1 = "Upgrade 1",
    RndWeaponBrute_Upgrade2 = "Upgrade 2",
    RndWeaponBrute_A_UpgradeDescription = "Random Brute class weapon Upgrade 1.",
    RndWeaponBrute_B_UpgradeDescription = "Random Brute class weapon Upgrade 2.",

    RndWeaponRanged_Name = "RND[Ranged]",
    RndWeaponRanged_Description = "Use random Ranged class weapon.",
    RndWeaponRanged_Upgrade1 = "Upgrade 1",
    RndWeaponRanged_Upgrade2 = "Upgrade 2",
    RndWeaponRanged_A_UpgradeDescription = "Random Ranged class weapon Upgrade 1.",
    RndWeaponRanged_B_UpgradeDescription = "Random Ranged class weapon Upgrade 2.",

    RndWeaponScience_Name = "RND[Science]",
    RndWeaponScience_Description = "Use random Science class weapon.",
    RndWeaponScience_Upgrade1 = "Upgrade 1",
    RndWeaponScience_Upgrade2 = "Upgrade 2",
    RndWeaponScience_A_UpgradeDescription = "Random Science class weapon Upgrade 1.",
    RndWeaponScience_B_UpgradeDescription = "Random Science class weapon Upgrade 2.",

    RndWeaponAny_Name = "RND[Any]",
    RndWeaponAny_Description = "Use random Any class weapon.",
    RndWeaponAny_Upgrade1 = "Upgrade 1",
    RndWeaponAny_Upgrade2 = "Upgrade 2",
    RndWeaponAny_A_UpgradeDescription = "Random Any class weapon Upgrade 1.",
    RndWeaponAny_B_UpgradeDescription = "Random Any class weapon Upgrade 2.",

    RndWeaponTechnoVek_Name = "RND[Cyborg]",
    RndWeaponTechnoVek_Description = "Use random Cyborg class weapon.",
    RndWeaponTechnoVek_Upgrade1 = "Upgrade 1",
    RndWeaponTechnoVek_Upgrade2 = "Upgrade 2",
    RndWeaponTechnoVek_A_UpgradeDescription = "Random Cyborg class weapon Upgrade 1.",
    RndWeaponTechnoVek_B_UpgradeDescription = "Random Cyborg class weapon Upgrade 2."
}
